ovsx:
  data:
    mirror:
      enabled: true
      server-url: https://open-vsx.org
      requests-per-second: 5
      user-name: mirror_user
      schedule:
        extensions: '* * * * * ? *'
        metadata: '* * * * * ? *'
      read-only:
        disallowed-methods: POST, PUT, PATCH, DELETE
        allowed-endpoints: /vscode/gallery/extensionquery, /admin/update-search-index, /api/-/query
      excluded-extensions:
        - vscode.*
        - redhat.vscode-yaml
